server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 默认 false 为 true 时 validationQuery 必须设为非空字符串
      # 【建议】配置为 true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效。
      test-while-idle: true
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 用来检测连接是否有效的 sql，要求是一个查询语句，常用 select 'x'。如果 validationQuery 为 null，
      # testOnBorrow、testOnReturn、testWhileIdle 都不会起作用。
      validation-query: select 1
      # 当前数据源操作类型
      type: com.alibaba.druid.pool.DruidDataSource
      # mysql 驱动包
      driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.169.169.181:3306/test1?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: esign
    password: esign
mybatis:
  mapperLocations: classpath:mapper/*.xml
  # 所有 entity 别名类所在包
  type-aliases-package: com.b19g3r.cloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 默认端口: 8761, 默认地址 htpp://localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka