server:
  port: 8761
eureka:
  instance:
    hostname: service1
    prefer-ip-address: true
  server:
    # 表示注册中心是否开启服务的自我保护能力, 默认为 true
    enable-self-preservation: true
    # 表示 Eureka Server 清理无效节点的频率，默认 60000 毫秒（60 秒）
    eviction-interval-timer-in-ms: 60000
  client:
    # false-不向注册中心注册自己
    register-with-eureka: false
    # false-表示自己端就是注册中心,职责是维护实例,并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群指向其它eureka
      defaultZone: http://service2:8762/eureka/
