server:
  port: 80
spring:
  application:
    name: cloud-order-service
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

#eureka:
#  instance:
#    instance-id: order80
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      # 默认端口: 8761, 默认地址 htpp://localhost:8761/eureka
#      # 单机版
#      # defaultZone: htpp://localhost:8761/eureka
#      # 集群版 注册所有的注册中心
#      defaultZone: http://service1:8761/eureka/, http://service2:8762/eureka/