server:
  port: 8082
spring:
  application:
    name: cloud-feign-order-service
eureka:
  instance:
    instance-id: order8082
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 默认端口: 8761, 默认地址 htpp://localhost:8761/eureka
      # 单机版
      # defaultZone: htpp://localhost:8761/eureka
      # 集群版 注册所有的注册中心
      defaultZone: http://service1:8761/eureka/, http://service2:8762/eureka/
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.b19g3r.cloud.service.IPaymentFeignService: debug